### ISSUE TITLE
Add bgzip output support

### ISSUE THREAD

**Issue by sstadick** [sstadick/perbase#10]
and indexing?

**Comment by nh13** [comment]
I second this request!

**Comment by nh13** [comment]
For now, folks can just pipe the output into `bgzip --index --index-name out.gz.csi > out.gz`

**Comment by sstadick** [comment]
In progress: https://github.com/sstadick/perbase/pull/36

Just need to update the README and look into generating an index.

It's not the fastest possible bgzip support, but it's better than nothing and probably still faster than piping into `bgzip` tool.

**Comment by sstadick** [comment]
See https://github.com/sstadick/perbase/pull/38

Skipping index generation for now.
