### ISSUE TITLE
read counter

### ISSUE THREAD

**Issue by colindaven** [sstadick/perbase#37]
nice tool, thanks.

Are you planning to integrated a pure read counter (per reference) option, surely you have the functionality already ? The only-depth is very close.

I use samtools idxstats for this at present, but am looking for independent confirmation for edge cases, etc.

Thanks

**Comment by sstadick** [comment]
I haven't used indexstats before. It looks like it just shows the total number of reads that mapped to each reference? 

I'm not currently planning on adding that to perbase, but that may change in the near future as I'm doing some updating. 

What is the edge case you are running into? https://github.com/biod/sambamba would likely be the best place to implement the same functionality.

**Comment by colindaven** [comment]
Yes, just total reads per bacterial/viral/human/fungal chromosome

Sambamba does not implement idxstats and it's written in D, so I'll pass. I'll supply a GTF/GFF to a tool like htseq-count or featureCounts for this then instead. However, that means a couple of extra dependencies in my metagenomic pipeline, which is not great. At least I can use internally for testing.

Thanks
