### ISSUE TITLE
'Chromosome not found in BAM/CRAM header'

### ISSUE THREAD

**Issue by Surar** [sstadick/perbase#50]
Hi, thanks for helping me with my previous Issue. I got an error message as below 

thread '<unnamed>' panicked at 'Chromosome not found in BAM/CRAM header', /opt/conda/conda-bld/perbase_1645626738058/work/src/lib/par_granges.rs:289:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 
however, there are chromosomes information in my file (I have attached the first page of it). so not sure what is the problem.
many thanks, Surar
<img width="1440" alt="Screenshot 2022-04-28 at 13 52 43" src="https://user-images.githubusercontent.com/66306766/165769023-410201f9-4de7-489d-9d53-d53a63a10af6.png">

**Comment by Surar** [comment]
the problem was in the bed file used with the option perbase base-depth -b.

many thanks

**Comment by paulahsan** [comment]
If anybody encountered this problem: I get rid of all the chromosome scaffolds/contigs and kept the regular chromosomes, 1:23, X,Y,M and error was gone.
