### ISSUE TITLE
(optional?) Dependencies don't allow perbase to be used or compiled on Ubuntu 18.04.

### ISSUE THREAD

**Issue by patbohn** [sstadick/perbase#55]
Dear perbase authors, 

thank you for your great tool, I have been looking for a while to find an optimized alignment parser. It works great as is on newer versions of Ubuntu, however on Ubuntu 18.04 neither the pre-compiled version works (due to a GLIBC 2.28+ requirement), nor is it compilable (due to cmake package requirement coming from the rust cmake 0.1.48 package. which uses the --parallel parameter that is not implemented in the cmake package available on Ubuntu 18.04). I could fix this by lowering the rust cmake package to 0.1.45, which as far as I could tell did not affect other things during compiling. 

https://github.com/sstadick/perbase/compare/master...patbohn:perbase_ubuntu18.04:master 

If you don't mind, you could lower the rust cmake package version to 0.1.45 (or maybe the documentatino in this Issue alone will help others with similar requirements). 

Best wishes, 
Patrick

**Comment by sstadick** [comment]
Hi Patrick! Thanks for making an issue!

I think my preferred method of fixing this would be to add another target to my CI jobs for Ubuntu 18.04 and get an updated cmake env installed in that environment. 

If there is a way to specify a sub-dependancy version that doesn't require altering the lock file I'd also be up for that. 

I'm not sure when I'll get to updating CI for this project to do that - but if you get something working I'm totally open to a PR.

**Comment by sstadick** [comment]
@patbohn - could you try out the binary here: https://github.com/sstadick/perbase/releases/tag/v0.8.5? I added Ubuntu-18.04 to my CI release matrix with the blind hope that it's using an older version of glibc and so should work on others Ubuntu 18.04 instances.

**Comment by patbohn** [comment]
Yes, that worked! Thanks :)
