### ISSUE TITLE
MacOS build on conda is incompatible with arm (but still gets installed)

### ISSUE THREAD

**Issue by patbohn** [sstadick/perbase#72]
When installing perbase via conda on an Arm Mac the package installs normally, but is not executable. As a workaround compiling from source works.

**Comment by camlloyd** [comment]
@patbohn, see https://github.com/bioconda/bioconda-recipes/pull/49210.

**Comment by camlloyd** [comment]
@patbohn, this issue should be resolved now.

**Comment by patbohn** [comment]
Can confirm it's working now. Thank you!
